kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: tsuki
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      
      location / {
        default_type application/json;
        return 200 "Suki!";
      }
    }